### ISSUE TITLE
403 after a bit when running `npx ts-node deploy.ts`

### ISSUE THREAD

**Issue by encho** [remotion-dev/github-unwrapped-2022#34]
Hello,
I am trying to run the `npx ts-node deploy.ts` command.

Functions and sites are successfully Deployed in `eu-central-1`, `eu-west-1`, `eu-west-2` and `eu-west-3`.
When it starts with `eu-south-1`, I get a 403 with `InvalidClientTokenId` reason. Do you know what it may be?

```
Ensured function "remotion-render-3-3-18-mem2048mb-disk2048mb-240sec" to eu-west-3 in account 1
Deployed site to eu-west-3 in account 1 under https://remotionlambda-euwest3-p7nydlv0ax.s3.eu-west-3.amazonaws.com/sites/unwrapped-2022-3.3.18/index.html
done region eu-west-3
start region eu-south-1
InvalidClientTokenId: The security token included in the request is invalid.
    at throwDefaultError (/Users/lorenzo/Desktop/softwarearchiv/jsvideo/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at deserializeAws_queryGetCallerIdentityCommandError (/Users/lorenzo/Desktop/softwarearchiv/jsvideo/node_modules/@aws-sdk/client-sts/dist-cjs/protocols/Aws_query.js:340:43)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/lorenzo/Desktop/softwarearchiv/jsvideo/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /Users/lorenzo/Desktop/softwarearchiv/jsvideo/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async StandardRetryStrategy.retry (/Users/lorenzo/Desktop/softwarearchiv/jsvideo/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /Users/lorenzo/Desktop/softwarearchiv/jsvideo/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async getAccountId (/Users/lorenzo/Desktop/softwarearchiv/jsvideo/node_modules/@remotion/lambda/dist/shared/get-account-id.js:9:28)
    at async deployFunction (/Users/lorenzo/Desktop/softwarearchiv/jsvideo/node_modules/@remotion/lambda/dist/api/deploy-function.js:46:23)
    at async execute (/Users/lorenzo/Desktop/softwarearchiv/jsvideo/deploy.ts:23:43) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 403,
    requestId: '9a97257b-0799-4382-8e4f-99155e2971cf',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Type: 'Sender',
  Code: 'InvalidClientTokenId'
}
```

Currently I ensure that I only use the successfully installed regions in the code. Does someone here know what the issue is with the problem above?

Many thanks!

**Comment by JonnyBurger** [comment]
@encho Most likely you need to enable this region in the AWS console: https://www.remotion.dev/docs/lambda/region-selection#enabling-regions-in-the-aws-console

I'll work on improving this error message!

**Comment by JonnyBurger** [comment]
Updated README and new documentation will soon go live within the next 15min: https://remotion.dev/docs/lambda/troubleshooting/security-token
